[package]
name = "tonic-grpc"
version = "0.1.0"
edition = "2018"

#[[bin]] # Bin to run the HelloWorld gRPC server
#name = "helloworld-server"
#path = "src/server.rs"

[dependencies]
tonic = "0.6"
prost = "0.9"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic-reflection = "0.3.0"

[build-dependencies]
tonic-build = "0.6"
